### ISSUE TITLE
Using with Rails 3.1

### ISSUE THREAD

**Issue by brendon** [RouL/html5shiv-js-rails#1]
Hi there, I was just wondering why the gemspec is so restrictive? I'd like to use this gem with Rails 3.1 :)

**Comment by RouL** [comment]
To be true, I'm not sure if the current version runs with Rails 3.1. At work I'm only working with Rails 4.x and in private projects I currently only use Rails 4.1. So I can't test it for Rails 3.x.

If you can test it and everything works (also that it's automatically compiled with rake assets:precompile for production) and tell me the railties version you did used, then I will fix the gemspec. :)

**Comment by brendon** [comment]
Thanks @RouL, for now I've just downloaded it and added it into the asset pipeline locally (since it's one file) :) If I have some spare time I'll fork it and give it a go :) I didn't think about the precompile thing! I assumed whatever was used to do the precompiling would be defined by the rails project itself rather than per each -rails asset pipeline gem :)

**Comment by RouL** [comment]
No problem @brendon. It's possible to do that in the project, but since html5shiv will be always included directly from with a script-tag instead of being included into the application.js via asset-pipeline, I thought it will be best to make sure you don't need to add it to the precompile list with: `Rails.application.config.assets.precompile += %w( html5shiv.js )`

With Rails 4.0 or 4.1 something changed, that's why I'm not sure if the current version will run properly with older Rails versions. You can see the change here: 304d1d0

**Comment by brendon** [comment]
Thanks @RouL :) I've just checked my project and I'm adding assets to the precompile array using the `+=` method, so you could probably loosen up the gemspec down to Rails 3.1 if you liked :)

**Comment by RouL** [comment]
I think at the weekend I will find some time. I will also check for new versions of html5shiv then.

**Comment by brendon** [comment]
Thanks Markus :)
